version: '2.3'

networks:
  mtr_local:

services:
  cldap:
    container_name: mtr-cldap
    restart: always
    networks:
     - mtr_local
    ports:
     - "389:389/udp"
    image: "mtr-cldap"
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
  # A Web-based service to view containers logs (Disabled by deafult).
  dozzle:
    container_name: dozzle
    restart: always
    # comment the profiles section to enable the service
    profiles:
      - donotstart
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9999:8080