name: publish
on: [push]
jobs:
publish-cldap-docker-image:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v2
- name: Login to GitHub Container Registry
uses: docker/login-action@v1
with:
registry: ghcr.io
username: ${{ github.actor }}
password: ${{ secrets.GITHUB_TOKEN }}
- name: Build the clDAP Honeypot Docker image
run: |
       docker build . --tag ghcr.io/im4kv/Malicious-Traffic-Research:cldap.latest
       docker run ghcr.io/im4kv/Malicious-Traffic-Research:cldap.latest
       docker push ghcr.io/im4kv/Malicious-Traffic-Research:cldap.latest
