name: publish
on: [push]
jobs:
  publish-cldap-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the cLDAP Honeypot Docker image
        run: |
              cd 'UDP 389 - cLDAP - DDoS Amplification'\docker
              docker build . --tag ghcr.io/im4kv/malicious-traffic-research:cldap.latest
              docker run ghcr.io/im4kv/malicious-traffic-research:cldap.latest
              docker push ghcr.io/im4kv/malicious-traffic-research:cldap.latest
